name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Release Asset
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: dantetimesync
            asset_name: dantetimesync-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: dantetimesync.exe
            asset_name: dantetimesync-windows-amd64.exe
            tray_artifact_name: dantetray.exe
            tray_asset_name: dantetray-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libgtk-3-dev

      - name: Run Tests (Linux Only)
        if: runner.os == 'Linux'
        run: cargo test --verbose

      - name: Run Tests (Windows Only)
        if: runner.os == 'Windows'
        run: cargo test --verbose

      - name: Build Main (Linux)
        if: runner.os == 'Linux'
        run: cargo build --release --bin dantetimesync --target ${{ matrix.target }} --verbose

      - name: Build Main & Tray (Windows)
        if: runner.os == 'Windows'
        run: cargo build --release --bin dantetimesync --bin dantetray --target ${{ matrix.target }} --verbose

      - name: Rename Artifacts (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Rename Artifacts (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}
          cp target/${{ matrix.target }}/release/${{ matrix.tray_artifact_name }} ${{ matrix.tray_asset_name }}

      - name: Upload Release Asset (Linux)
        if: runner.os == 'Linux'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}
          generate_release_notes: true

      - name: Upload Release Asset (Windows)
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.asset_name }}
            ${{ matrix.tray_asset_name }}
          generate_release_notes: true
