name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Release Asset
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: dantetimesync
            asset_name: dantetimesync-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: dantetimesync.exe
            asset_name: dantetimesync-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Install WinPcap SDK (Windows Only)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip -OutFile WpdPack.zip
          Expand-Archive WpdPack.zip -DestinationPath .
          echo "LIB=$PWD\WpdPack\Lib\x64;$env:LIB" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Run Tests (Linux Only)
        if: runner.os == 'Linux'
        run: cargo test --verbose

      - name: Build
        run: cargo build --release --target ${{ matrix.target }} --verbose

      - name: Rename Artifact
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}
          generate_release_notes: true
